import type { GameProject } from "./project-types";
import { builtInSprites, builtInSyracuseScene } from "./builtin-sprites";

export function createDefaultProject(): GameProject {
  return {
    schemaVersion: 1,
    game: "Life is a Gamble",
    updatedAt: "2026-08-14T00:00:00.000Z",
    levels: [
      {
        id: "syracuse-salt-yard",
        name: "Syracuse · Salt Yard",
        region: "Upstate Wastes",
        description: "A dense downtown approach built around Clinton Square and the old canal corridor.",
        environment: "ruined-city-dusk",
        width: 100,
        height: 100,
        gridSize: 10,
        playerSpawn: { x: 50, y: 72 },
      },
    ],
    cells: [
      {
        id: "clinton-square",
        levelId: "syracuse-salt-yard",
        name: "Clinton Square",
        kind: "exterior",
        x: 8,
        y: 45,
        width: 42,
        height: 38,
        ambience: "salt-wind",
        notes: "Primary arrival cell and Rowan encounter space.",
        doors: [
          {
            id: "supply-door",
            name: "Clinton Provisioners",
            edge: "north",
            targetLevelId: "syracuse-salt-yard",
            targetCellId: "provisioners-interior",
            loadMode: "locked",
            locked: true,
            keyId: "provisioners-key",
          },
        ],
      },
      {
        id: "provisioners-interior",
        levelId: "syracuse-salt-yard",
        name: "Clinton Provisioners",
        kind: "interior",
        x: 58,
        y: 8,
        width: 30,
        height: 28,
        ambience: "interior-dust",
        notes: "Locked shop interior with searchable stock cage.",
        doors: [],
      },
    ],
    spriteAssets: builtInSprites(),
    levelLayers: [
      { id: "syracuse-terrain", levelId: "syracuse-salt-yard", name: "Terrain", kind: "terrain", visible: true, locked: false, opacity: 1 },
      { id: "syracuse-objects", levelId: "syracuse-salt-yard", name: "Objects", kind: "objects", visible: true, locked: false, opacity: 1 },
      { id: "syracuse-collision", levelId: "syracuse-salt-yard", name: "Collision", kind: "collision", visible: true, locked: false, opacity: 0.65 },
      { id: "syracuse-entities", levelId: "syracuse-salt-yard", name: "Entities", kind: "entities", visible: true, locked: false, opacity: 1 },
    ],
    levelObjects: builtInSyracuseScene("syracuse-objects", "syracuse-entities"),
    lootTables: [
      {
        id: "street-cache-common",
        name: "Street Cache · Common",
        rolls: 2,
        allowDuplicates: false,
        entries: [
          { id: "loot-chips", itemId: "old-chips", itemName: "Old-world Chips", chance: 72, weight: 50, min: 2, max: 9, condition: "" },
          { id: "loot-bandage", itemId: "field-bandage", itemName: "Field Bandage", chance: 35, weight: 25, min: 1, max: 2, condition: "player.level >= 1" },
        ],
      },
    ],
    npcs: [
      {
        id: "rowan-vale",
        name: "Rowan Vale",
        role: "Wanderer / potential companion",
        faction: "Independent",
        hostile: false,
        level: 4,
        health: 28,
        armor: 3,
        personality: "Wary, dryly funny, practical, private, and slow to trust.",
        dialogueStyle: "Short, observant sentences. Deflects with questions when motives are unclear.",
        motivation: "Map a survivable western route without owing Albany a favor.",
        fears: "Becoming responsible for another doomed traveler.",
        traits: ["candor-sensitive", "cartographer", "slow-trust"],
        likes: ["maps", "coffee", "competence"],
        dislikes: ["threats", "Citadel clerks", "empty heroics"],
        inventoryLootTableId: "street-cache-common",
        dropLootTableId: "street-cache-common",
      },
      {
        id: "rabid-squirrel",
        name: "Rabid Squirrel",
        role: "Wildlife threat",
        faction: "Feral",
        hostile: true,
        level: 1,
        health: 12,
        armor: 0,
        personality: "Territorial, frantic, hunger-driven.",
        dialogueStyle: "Nonverbal.",
        motivation: "Defend its nest and feed.",
        fears: "Fire and sustained noise.",
        traits: ["fast", "feral", "disease-carrier"],
        likes: [],
        dislikes: ["fire", "noise"],
        inventoryLootTableId: "",
        dropLootTableId: "street-cache-common",
      },
    ],
    spawners: [
      {
        id: "squirrel-alley-spawner",
        name: "Squirrel Alley",
        levelId: "syracuse-salt-yard",
        cellId: "clinton-square",
        x: 75,
        y: 65,
        radius: 8,
        maxAlive: 2,
        cooldownSeconds: 90,
        enabled: true,
        entries: [{ id: "spawn-rabid-squirrel", npcId: "rabid-squirrel", chance: 65, weight: 100, minGroup: 1, maxGroup: 2 }],
      },
    ],
    quests: [
      {
        id: "courthouse-ledger",
        title: "The Courthouse Ledger",
        summary: "Follow Rowan's rumor to a pre-Silence ledger beneath the courthouse.",
        giverNpcId: "rowan-vale",
        repeatable: false,
        hidden: false,
        triggers: [{ id: "trigger-rowan-rumor", type: "world_flag", targetId: "Rumor unlocked: The Courthouse Ledger", operator: "is", value: "true" }],
        tasks: [
          { id: "task-enter-courthouse", title: "Reach the courthouse undercroft", type: "visit", targetId: "courthouse-undercroft", count: 1, optional: false },
          { id: "task-find-ledger", title: "Recover the continuity ledger", type: "collect", targetId: "continuity-ledger", count: 1, optional: false },
        ],
        completionMode: "all_required",
        completionRequirements: "The Courier possesses continuity-ledger and has not surrendered it to another faction.",
        rewards: [
          { id: "reward-ledger-xp", type: "xp", targetId: "player", amount: 80 },
          { id: "reward-ledger-flag", type: "world_flag", targetId: "Ledger recovered", amount: 1 },
        ],
      },
    ],
  };
}
